// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyyvnsfghvgjuorslayk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eXZuc2ZnaHZnanVvcnNsYXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzAzODYsImV4cCI6MjA2MDIwNjM4Nn0.GxB7RtvQTcYQKNBwfWd_dyM7tJFpE7qjyBx25Bqx6OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);